package ch.obermuhlner.planetgen.planet.texture;

public enum TextureType {
	DIFFUSE,
	NORMAL,
	SPECULAR,
	LUMINOUS,
	HEIGHT,
	PRECIPITATION,
	PRECIPITATION_AVERAGE,
	THERMAL,
	THERMAL_AVERAGE,
	ATMOSPHERIC_PRESSURE,
	CLOUD,
	DEBUG,
}